# Generated by Django 2.0.6 on 2018-06-17 05:48

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='created')),
                ('_data', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('formatted_address', models.TextField(blank=True, verbose_name='formatted address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'geolocation',
                'verbose_name_plural': 'geolocations',
            },
        ),
    ]
